version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tastybite_db
      POSTGRES_USER: tastybite_user
      POSTGRES_PASSWORD: tastybite_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tastybite_user -d tastybite_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://tastybite_user:tastybite_password@db:5432/tastybite_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-this-in-production
      ENVIRONMENT: development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m app.main

volumes:
  postgres_data: